### PR TITLE
Fix ExpressionFunctions.ColorLerpRgb

### LINKED ISSUE #303: ExpressionFunctions.ColorLerpRgb does not work
### Describe the bug

The `ExpressionFunctions.ColorLerpRgb` does not work.

image
image

### Steps to reproduce

```text
Start a color animation with `ExpressionFunctions.ColorLerpRgb`.
```

### Expected behavior

The animation should work as expected.

### Screenshots

_No response_

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

_No response_

### Visual Studio Build Number

_No response_

### Device form factor

_No response_

### Additional context

_No response_

### Help us help you

Yes, I'd like to be assigned to work on this item.

### PR DESCRIPTION
**Pull request by h82258652**
## Fixes

#303 

## PR Type

What kind of change does this PR introduce?

 - Bugfix

## What is the current behavior?

The app will be crashed if the code uses `ExpressionFunctions.ColorLerpRgb`.

## What is the new behavior?

The app won't be crashed and the animation works as expected.

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [ ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [ ] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (if applicable)
- [ ] Header has been added to all new source files
- [x] Contains **NO** breaking changes

### CODE REVIEW

File: components/Animations/tests/Test_ExpressionFunctions.cs [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        var temp = ExpressionFunctions.ColorRgb(255f, 255f, 0f, 0f);
+        var color = ExpressionFunctions.ColorLerpRgb(temp, temp, 0.5f);
+
+        brush.StartAnimation("Color", color);
+
+        var visual = compositor.CreateSpriteVisual();
+        visual.Brush = brush;
+        visual.RelativeSizeAdjustment = Vector2.One;
+
+        ElementCompositionPreview.SetElementChildVisual(rootGrid, visual);
```
Comment (michael-hawker) [inline components/Animations/tests/Test_ExpressionFunctions.cs:39]: @Arlodotexe should there be any asserts or other checks here or anything? Basically this is just a runtime pass/fail check I guess if there's an exception?

**Comment by lindexi** [comment]
Awesome
