### PR TITLE
Orientation option for Segmented 

### LINKED ISSUE #746: [Segmented] Orientation Property
### Describe the bug

It'd be nice to see an `Orientation` property on the Segmented control.

This could be used for simpler modern navigation view styles, e.g.

Image

Or other small vertical only toolbars (my use-case), etc...

I believe this would mainly need an update to `EqualPanel` to support Orientation, and then expose that up to the parent `Segmented` control. I'm not sure what other design considerations would be needed.

Having a small icon-only based sample and a more nav-view-esque style with larger blocks with labels would be good additions for this new experience.

### Steps to reproduce

```text
N/A
```

### Expected behavior

Able to orient segmented control vertically as well.

### Screenshots

_No response_

### Code Platform

- [x] UWP
- [x] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

_No response_

### Visual Studio Build Number

_No response_

### Device form factor

_No response_

### Additional context

_No response_

### Help us help you

Yes, but only if others can assist.

### PR DESCRIPTION
**Pull request by Avid29**
## PR Type

What kind of change does this PR introduce?

## What is the current behavior?

There is not orientation options for the Segmented control

## What is the new behavior?

Add customization options for a vertical Segmented control

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] Tested code with current supported SDKs
- [x] Tests for the changes have been added (if applicable)
- [x] Header has been added to all new source files
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by Avid29** [comment]
So far I've added an `Orientation` property to the `EqualPanel`. I tested it (see below), but it's not actually implemented anywhere yet.

image

**Comment by Avid29** [comment]
Here's an update.
image

Though this does have a slight change in the horizontal style, namely the selected indicator is centered on the full `SegmentedItem` rather than just the content. Here's what that difference looks like in practice.

Before:
image
After:
image

**Comment by michael-hawker** [comment]
@niels9001 was there a reason the indicator was centered under the content only vs. the entire content? That'll only matter in Icon + Text Horizontal mode.

**Comment by michael-hawker** [comment]
@Avid29 this works perfect!

image

Just slotted right into my VSM with changing the orientation and I was done! 🦙❤️ I'll take a look through the code itself in a bit.

File: components/Segmented/src/Segmented/Segmented.cs [hunk 1]
```diff
@@ -154,4 +155,16 @@ private void OnSelectedIndexChanged(DependencyObject sender, DependencyProperty
...
+
+    private void OnOrientationChanged()
+    {
+        for (int i = 0; i < Items.Count; i++)
+        {
+            var container = ContainerFromIndex(i) as SegmentedItem;
+            if (container is null)
+                continue;
+
+            container.UpdateOrientation(Orientation);
```
Comment (michael-hawker) [inline components/Segmented/src/Segmented/Segmented.cs]:
```suggestion
            if (ContainerFromIndex(i) is SegmentedItem item)
            {
                item.UpdateOrientation(Orientation);
            }
```
Would this be simpler?

File: components/Segmented/src/SegmentedItem/SegmentedItem.cs [hunk 2]
```diff
@@ -2,6 +2,8 @@
 // The .NET Foundation licenses this file to you under the MIT license.
 // See the LICENSE file in the project root for more information.
 
+using Windows.Media.Devices;
+
```
Comment (michael-hawker) [inline components/Segmented/src/SegmentedItem/SegmentedItem.cs]: Accidental namespace add?

**Review by michael-hawker — COMMENTED** [review]
Looks pretty clean to me. @niels9001 @Arlodotexe let me know your thoughts.

File: components/Segmented/src/SegmentedItem/SegmentedItem.cs (hunk 2 above)
Comment (Avid29) [reply components/Segmented/src/SegmentedItem/SegmentedItem.cs]: Yeah. Visual Studio really just adds whatever as I type and I often forget to even check 🤷

File: components/Segmented/src/Segmented/Segmented.cs (hunk 1 above)
Comment (Avid29) [reply components/Segmented/src/Segmented/Segmented.cs]: Yeah. I have a tendency to over user guard checks...

File: components/Segmented/src/Segmented/Segmented.cs [hunk 3]
```diff
@@ -22,6 +22,7 @@ public Segmented()
         this.DefaultStyleKey = typeof(Segmented);
 
         RegisterPropertyChangedCallback(SelectedIndexProperty, OnSelectedIndexChanged);
+        RegisterPropertyChangedCallback(OrientationProperty, OnSelectedIndexChanged);
```
Comment (AndrewKeepCoding) [inline components/Segmented/src/Segmented/Segmented.cs]: Would it make sense to extract the logic in `OnSelectedIndexChanged` into a `SaveInitialIndex` method then call it from `OnSelectedIndexChanged` and `OnOrientationChanged`?

File: components/Segmented/src/EqualPanel.cs [hunk 4]
```diff
@@ -60,19 +80,39 @@ protected override Size MeasureOverride(Size availableSize)
...
+            double availableU = Orientation is Orientation.Horizontal ? availableSize.Width : availableSize.Height;
+
+            if (stretch)
             {
-                return new Size((_maxItemWidth * _visibleItemsCount) + (Spacing * (_visibleItemsCount - 1)), _maxItemHeight);
+                // Adjust maxItemU to form equal rows/columns by available U space (adjust for spacing)
+                double totalU = availableU - (Spacing * (_visibleItemsCount - 1));
+                maxItemU = totalU / _visibleItemsCount;
+
+                // Set uSize/vSize for XY result contstruction
```
Comment (AndrewKeepCoding) [inline components/Segmented/src/EqualPanel.cs]:
```suggestion
                // Set uSize/vSize for XY result construction
```

File: components/Segmented/src/Segmented/Segmented.cs (hunk 3 above)
Comment (Avid29) [reply components/Segmented/src/Segmented/Segmented.cs]: Oh, I see. Because I moved the callback to the DependencyProperty declaration. This line is entirely unnecessary.

**Comment by Avid29** [comment]
This is now blocking for #752

**Comment by niels9001** [comment]
image

Horizontal center alignment of the pill under the label is per design spec. But I'm fine with this change as this would align it with `NavigationView` too.

**Comment by Avid29** [comment]
@niels9001 I believe I could get the pill back under the content by finagling the column layout and visual state setters, but as is now I believe it makes the default style's layout more predictable. It might even be simpler if I adjust the default `VisualState` (though they're always set, so it wouldn't change any behavior).

File: components/Segmented/src/EqualPanel.cs [hunk 5]
```diff
@@ -60,19 +79,39 @@ protected override Size MeasureOverride(Size availableSize)
 
         if (_visibleItemsCount > 0)
         {
-            // Return equal widths based on the widest item
-            // In very specific edge cases the AvailableWidth might be infinite resulting in a crash.
-            if (HorizontalAlignment != HorizontalAlignment.Stretch || double.IsInfinity(availableSize.Width))
+            bool stretch = Orientation switch
```
Comment (Arlodotexe) [inline components/Segmented/src/EqualPanel.cs]: The original code comments here need to be preserved, especially:

>  // In very specific edge cases the AvailableWidth might be infinite resulting in a crash.

**Comment by Avid29** [comment]
> @niels9001 I believe I could get the pill back under the content by finagling the column layout and visual state setters, but as is now I believe it makes the default style's layout more predictable. It might even be simpler if I adjust the default `VisualState` (though they're always set, so it wouldn't change any behavior).

I looked into it. I'd forgotten that to get the pill to left align properly I had to move it outside of the `ContentHolder`. This makes it much much harder, since it's no longer a child of the grid separating the icon from the content.

**Comment by niels9001** [comment]
image
 
 This also happened.. I think it's expected, and probably up to the developer to not use `Stretch` in vertical mode, right?

**Comment by Avid29** [comment]
Hmm. Yeah, idk what expected behavior is there. You're definitely right that I should add options to more of the samples though.

**Comment by Avid29** [comment]
> 3. Have we tested the vertical orientation with the built-in styles too? Could we add an orientation dropdown to this sample too so it's easier to validate any changes in the future?

Yes, I did think about this. I explcitly decided that the `PivotSegmentedStyle` ignores the property, though to be honest it would be quite harmless to make it stack, same as `ButtonSegmentedStyle`. Here's a screenshot with that sample option added.

image

**Comment by Avid29** [comment]
> 1. Long text labels don't fit.. Maybe we should use texttrimming for this so it just ... for the chars that no longer fit?

I'd noticed this, and looked into that. The issue is `TextTrimming` is a `TextBlock` property not found on the `ContentPresenter`. I'm not sure how this can be added.

**Comment by Avid29** [comment]
> 2. It feels like we need a bit more spacing vertically (maybe 4 instead of 1) by default to better differentiate what icon belongs to what label. Should we introduce a HorizontalSegmentedItemSpacing and VerticalSegmentedItemSpacing?

I fiddled with the margins a bit more, and adjusted which UIElements contain the margins to be more sensible. This is the results. Thoughts? It also fixes the long item's text being cutoff on the left.

image

**Review by Arlodotexe — DISMISSED** [review]
Tested locally, all works as expected. Comments are for code cleanup and clarifications.

**Comment by michael-hawker** [comment]
> > 3. Have we tested the vertical orientation with the built-in styles too? Could we add an orientation dropdown to this sample too so it's easier to validate any changes in the future?
> 
> Yes, I did think about this. I explcitly decided that the `PivotSegmentedStyle` ignores the property, though to be honest it would be quite harmless to make it stack, same as `ButtonSegmentedStyle`. Here's a screenshot with that sample option added.
> 
> image

Might as well update Pivot Style for completeness? I assume the pill would also go to the left like it does with the default style?

CI failure is due to the failing test (which I think is an external issue, needs confirmation).

**Comment by niels9001** [comment]
> > 2. It feels like we need a bit more spacing vertically (maybe 4 instead of 1) by default to better differentiate what icon belongs to what label. Should we introduce a HorizontalSegmentedItemSpacing and VerticalSegmentedItemSpacing?
> 
> I fiddled with the margins a bit more, and adjusted which UIElements contain the margins to be more sensible. This is the results. Thoughts? It also fixes the long item's text being cutoff on the left.
> 
> image

Looking at your screenshot, it looks like the icon/text label are not correctly center aligned?

image

**Comment by Avid29** [comment]
> > > 2. It feels like we need a bit more spacing vertically (maybe 4 instead of 1) by default to better differentiate what icon belongs to what label. Should we introduce a HorizontalSegmentedItemSpacing and VerticalSegmentedItemSpacing?
> > 
> > 
> > I fiddled with the margins a bit more, and adjusted which UIElements contain the margins to be more sensible. This is the results. Thoughts? It also fixes the long item's text being cutoff on the left.
> > image
> 
> Looking at your screenshot, it looks like the icon/text label are not correctly center aligned?
 
Hmm... This is actually really affirming to hear because I had noticed it felt off, but by all means it appears it should be symmetrical according to the code so I assumed I was just wrong. I'll look closer now and see what I can do.

**Comment by Avid29** [comment]
Fixed the alignment issues. It was caused by centering the grid on the content, which would misalign the icon by 1 pixel if the content had an odd with.

I also overrode the hover margins when in the vertical state, which I has missed before.

image

File: components/Segmented/src/EqualPanel.cs [hunk 6]
```diff
@@ -60,19 +79,39 @@ protected override Size MeasureOverride(Size availableSize)
...
+            {
+                Orientation.Horizontal => HorizontalAlignment is HorizontalAlignment.Stretch && !double.IsInfinity(availableSize.Width),
+                Orientation.Vertical or _ => VerticalAlignment is VerticalAlignment.Stretch && !double.IsInfinity(availableSize.Height),
+            };
+
+            // Define XY coords
+            double xSize = 0, ySize = 0;
+
+            // Define UV coords for orientation agnostic XY manipulation
+            ref double uSize = ref SelectAxis(Orientation, ref xSize, ref ySize, true);
```
[the remark this answers is not in the document]
Comment (michael-hawker) [reply components/Segmented/src/EqualPanel.cs]: Cool, thanks for the explanation, always good to learn new stuff. 🦙❤️ Also, sometimes h easy to miss the tiny keywords. 😅

**Comment by michael-hawker** [comment]
Sorry @Avid29 I should have merged maybe for the main update vs. rebase as you're working on this. Wanted to pick up the fixes for the tests to be more reliable for the CI.

**Comment by Avid29** [comment]
No problem 👍

File: components/Segmented/src/EqualPanel.cs [hunk 7]
```diff
@@ -32,14 +24,41 @@ public double Spacing
...
+        new PropertyMetadata(default(double), OnPropertyChanged));
+
+    /// <summary>
+    /// Backing <see cref="DependencyProperty"/> for the <see cref="Orientation"/> property.
+    /// </summary>
+    public static readonly DependencyProperty OrientationProperty = DependencyProperty.Register(
+        nameof(Orientation),
+        typeof(Orientation),
+        typeof(EqualPanel),
+        new PropertyMetadata(default(Orientation), OnPropertyChanged));
```
[the remark this answers is not in the document]
Comment (Arlodotexe) [reply components/Segmented/src/EqualPanel.cs]: > Why does it need to be disambiguated?

Because other DP change callbacks exist in this class.

**Comment by michael-hawker** [comment]
Held up by #758

**Comment by michael-hawker** [comment]
Hopefully CI issues are resolved now. Think there's just a few small comments left and for @niels9001 to approve if the new style changes look good?

**Comment by Avid29** [comment]
Looks like the CI is fine. The issue is just using ref fields in UWP. Hmm...

**Review by niels9001 — APPROVED** [review]
The visual changes look great to me :)! Thanks a lot @Avid29 !

**Comment by lgztx96** [comment]
I noticed that the PR adding Orientation support to Segmented has already been merged, but I encountered issues during testing while porting this to the C++ version.

In vertical mode, the pill should be positioned on the left, but it is currently rendered below. Because the Orientation property is changed during initialization before the item is added to the container, Item state updates rely on the Orientation property change callback, so dynamically binding the ItemSource may also result in incorrect behavior.

This can be reproduced simply by setting the following XAML:
```xml
 <controls:Segmented Orientation="Vertical">
     <controls:SegmentedItem Content="Item 1" />
     <controls:SegmentedItem Content="Item 2" />
     <controls:SegmentedItem Content="Item 3" />
     <controls:SegmentedItem Content="Item 4" />
 </controls:Segmented>
```
Alternatively, set the default value of Orientation to Vertical in the sample application.

Image

**Comment by Avid29** [comment]
@lgztx96 Good catch! On it.
